### ISSUE TITLE
Add options for multiple display environment

### ISSUE THREAD

**Issue by Canorus** [pjessesco/ChollianWallPaper#35]
macOS Monterey 12.5

I'm using 2 displays, one in landscape orientation and another in portrait(so this may be inclusive to issue #24), and CWP tries to set Wallpaper on both displays, while setting to only one would be desirable. Maybe adding an option to select display based on  device id can help.

Thanks.

**Comment by pjessesco** [comment]
Hi, I'll close this issue since it's duplicated with #24 (and maybe #25 in your case). These are definitely one of the highest priority issues, but I'm not sure when it will be developed due to it's complexity (Multiple screens/desktops, following UI/UX, etc).
